SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL, MEMBER_ADDR, 
			TO_CHAR( ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"' ) ENROLL_DATE, CODE_NO
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N'
AND MEMBER_EMAIL = 'petnolza@kh.or.kr';

UPDATE "MEMBER" SET MEMBER_PASSWORD = '$2a$10$AB2ma2FooGY7zsW9YTudout53WhWhzxr9BW/TMxuebpDcCGrOQd5W'
WHERE MEMBER_NO = '2';

ALTER TABLE "MEMBER" MODIFY (MEMBER_PASSWORD NVARCHAR2(100));

COMMIT;

SELECT * FROM "MEMBER";

ALTER TABLE "MEMBER" MODIFY (CODE_NO DEFAULT 'NORMAL');

ALTER TABLE "MEMBER" MODIFY (MEMBER_TEL NOT NULL);