-- 1번 문제--

SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;


-- 2번 문제 --(|| 연결 연산자 사용)

SELECT TO_CHAR (DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' ) "학과별 정원"
FROM TB_DEPARTMENT;

-- 3번 문제 --

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE TB_STUDENT.ABSENCE_YN = 'Y' 
	AND TB_STUDENT.DEPARTMENT_NO = 001
	AND SUBSTR( TB_STUDENT.STUDENT_SSN ,8 , 1 ) = 2;

-- 4번 문제 -- (IN 연산자 + 내림차순 (DESC))
SELECT STUDENT_NAME
FROM TB_STUDENT ts 
WHERE TS.STUDENT_NO 
IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;
 
-- 5번 문제 --
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT td 
WHERE TD.CAPACITY >= 20 AND TD.CAPACITY <= 30;
-- CAPACITY BETWEEN 20 AND 30; --

-- 6번 문제 --
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR tp 
WHERE TP.DEPARTMENT_NO IS NULL;

-- 7번 문제 --
SELECT STUDENT_NAME
FROM TB_STUDENT ts 
WHERE TS.DEPARTMENT_NO IS NULL;

-- 8번 문제 --
SELECT CLASS_NO
FROM TB_CLASS tc 
WHERE TC.PREATTENDING_CLASS_NO IS NOT NULL;

-- 9번 문제 -- (중복 제거 DISTINCT + 오름차순 정렬)
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT td 
ORDER BY CATEGORY;

-- 10번 문제 --
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT ts 
WHERE TS.STUDENT_ADDRESS LIKE '전주%'
     AND (TS.ENTRANCE_DATE BETWEEN '2002-01-01' AND '2002-12-31')
     AND TS.ABSENCE_YN = 'N';

-- 풀이 --    
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002
	AND STUDENT_ADDRESS LIKE '전주%'
	AND ABSENCE_YN = 'N';




























